quotes_list = ("Start your day with gratitude.",
               "Take a deep breath, you've got this.",
               "Practice kindness, always.",
               "Set realistic goals for the day.",
               "Smile—it's contagious.",
               "Prioritize self-care.",
               "Focus on progress, not perfection.",
               "Drink water, stay hydrated.",
               "Embrace change with an open mind.",
               "Express your feelings, don't bottle them up.",
               "Learn something new today.",
               "Be present in the moment.",
               "Surround yourself with positivity.",
               "Find joy in the little things.",
               "Believe in your abilities.",
               "Take a break when needed.",
               "Connect with a friend or loved one.",
               "Organize your space for clarity.",
               "Challenge negative thoughts.",
               "Celebrate your achievements, big or small.",
               "Practice mindfulness.",
               "Listen more than you speak.",
               "Step outside your comfort zone.",
               "Accept imperfections, yours and others'.",
               "Laugh often—it's good for the soul.",
               "Stay curious and ask questions.",
               "Face challenges with resilience.",
               "Take a moment to appreciate nature.",
               "Practice active listening.",
               "Trust the process of life.",
               "Reflect on your day before sleep.",
               "Acknowledge and learn from mistakes.",
               "Practice patience with yourself and others.",
               "Keep a positive mindset.",
               "Be mindful of your energy.",
               "Exercise for a happy mind and body.",
               "Express gratitude for challenges—they build resilience.",
               "Practice deep breathing for relaxation.",
               "Choose happiness over perfection.",
               "Be your own biggest supporter.",
               "Disconnect from technology for a while.",
               "Believe in the power of your dreams.",
               "Celebrate the success of others.",
               "Face fears head-on.",
               "Learn to say no when necessary.",
               "Challenge negative self-talk.",
               "Plan for a restful night's sleep.",
               "Seek out inspiration daily.",
               "Be gentle with yourself on tough days.",
               "Learn to forgive, for your own peace.",
               "Practice random acts of kindness.",
               "Trust the timing of your life.",
               "Set boundaries on social media.",
               "Reflect on three things you're grateful for today.",
               "Focus on solutions, not problems.",
               "Take a digital detox.",
               "Make time for a hobby you enjoy.",
               "Let go of what you can't control.",
               "Face challenges with a positive attitude.",
               "Share your talents with the world.",
               "Connect with someone new today.",
               "Find joy in the simple pleasures.",
               "Visualize your goals coming to fruition.",
               "Be mindful of your thoughts—they shape your reality.",
               "Practice self-compassion.",
               "Learn from criticism without taking it personally.",
               "Surround yourself with uplifting people.",
               "Challenge yourself to learn from setbacks.",
               "Speak words of encouragement to yourself.",
               "Create a vision board for your dreams.",
               "Practice gratitude in challenging situations.",
               "Set aside time for self-reflection.",
               "Celebrate progress, no matter how small.",
               "Release the need for approval from others.",
               "Declutter your physical and mental space.",
               "Practice the art of letting go.",
               "Believe in your own worthiness.",
               "Express love to those around you.",
               "Trust the journey, even when it's uncertain.",
               "Take a break from multitasking.",
               "Appreciate the journey as much as the destination.",
               "Believe in the power of positive thinking.",
               "Face challenges with courage and strength.",
               "Express your creativity in some way.",
               "Practice self-discipline for personal growth.",
               "Trust yourself—you know more than you think.",
               "Make choices that align with your values.",
               "Focus on what you can control.",
               "Practice gratitude for your body and health.",
               "Be kind to yourself during times of stress.",
               "Reflect on how far you've come.",
               "Find joy in helping others.",
               "Face challenges as opportunities for growth.",
               "Express your needs and desires clearly.",
               "Learn to let go of perfectionism.",
               "Take time to appreciate the beauty around you.",
               "Embrace the power of saying 'no' when necessary.",
               "Believe in the potential for positive change.",
               "Choose love over fear in decision-making.",
               "Celebrate your uniqueness.",
               "Practice patience in all aspects of life.")
